"""Generate the same fragment effect for standalone Niri and shell presets."""

from dataclasses import asdict, dataclass
from importlib.resources import files
import math


@dataclass(frozen=True)
class Effect:
    tile_size: float = 28
    scatter: float = 90
    open_ms: int = 420
    close_ms: int = 320

    def __post_init__(self):
        for name, low, high in (("tile_size", 8, 128), ("scatter", 0, 240),
                                ("open_ms", 100, 1500), ("close_ms", 100, 1500)):
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or not low <= value <= high:
                raise ValueError(f"{name} must be a finite number between {low} and {high}")
            if name.endswith("_ms") and int(value) != value:
                raise ValueError(f"{name} must be a whole number")


PRESETS = {
    "subtle": Effect(24, 45, 320, 240),
    "balanced": Effect(),
    "dramatic": Effect(36, 160, 550, 420),
}


def shader(effect, opening):
    template = files("niri_fragments").joinpath("shaders/fragments.glsl").read_text()
    return (template.replace("@TILE@", f"{effect.tile_size:.6f}")
            .replace("@SCATTER@", f"{effect.scatter:.6f}")
            .replace("@ENTRY@", "open_color" if opening else "close_color")
            .replace("@PROGRESS@", "1.0 - niri_clamped_progress" if opening else "niri_clamped_progress"))


def animation_types(effect):
    return {
        name: {"duration-ms": duration, "curve": "linear", "custom-shader": shader(effect, opening)}
        for name, duration, opening in (("window-open", effect.open_ms, True),
                                        ("window-close", effect.close_ms, False))
    }


def render_kdl(effect):
    parts = ["// Generated by niri-fragments. Include after your base animation settings.", "animations {"]
    for name, spec in animation_types(effect).items():
        parts.extend([f"    {name} {{", f"        duration-ms {int(spec['duration-ms'])}",
                      '        curve "linear"', '        custom-shader r"',
                      spec["custom-shader"].rstrip(), '        "', "    }"])
    return "\n".join([*parts, "}", ""])


def preset_description(effect):
    return f"{effect.tile_size:g}px pieces, {effect.scatter:g}px scatter; {effect.open_ms}/{effect.close_ms}ms open/close."


def describe_presets():
    return {name: asdict(effect) for name, effect in PRESETS.items()}
