#!/usr/bin/env python3
"""Compare continuous fragment presets in an owned, temporary Niri session.

The synthetic cards request only allowlisted preset names through their own logs.
This process owns the sole config writer and never accepts a destination path.
It is a source-checkout experiment, not an installation or a background service.
"""

import argparse
import json
import os
import re
import signal
import sys
import time
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from lib.fragment import FragmentSession, config, experiment
from lib.nested import wait_for

from niri_fx.capabilities import fragment_capability
from niri_fx.fragment_motion import PRESETS
from niri_fx.storage import atomic_write

BINDS = """
binds {
    Alt+Left { move-column-left; }
    Alt+Right { move-column-right; }
    Alt+F { toggle-window-floating; }
    Alt+Q { quit skip-confirmation=true; }
}
"""
REQUEST = re.compile(r"(?:^|\s)NIRIFX_PRESET (gentle|tear|cascade|off)$")


def requests(stream):
    """Read bounded batches; logs are data and cannot name paths or commands."""
    for line in stream.readlines(8192):
        match = REQUEST.search(line.rstrip())
        if match:
            yield match[1]


def status(preset_name, enabled):
    preset = PRESETS[preset_name]
    return {
        "preset": preset_name if enabled else "off",
        "name": preset.name if enabled else "Off",
        "description": preset.description if enabled else "Movement animation disabled.",
        "particles": preset.particles if enabled else 0,
        "settings": asdict(preset.settings),
        "hint": "Release, let the pieces settle, then drag again to compare.",
    }


def run(preset_name):
    binary, build = experiment()
    enabled = True
    with FragmentSession(config(preset_name) + BINDS, binary=binary) as session:
        capability = fragment_capability(binary, socket_path=session.env["NIRI_SOCKET"])
        if not capability["activation_ready"] or not capability["session"].get("contract", {}).get(
            "fragment_enabled"
        ):
            raise RuntimeError(f"Continuous fragments unavailable: {capability}")
        session.check_render_log()
        state_path = session.root / "fragment-demo-status.json"
        atomic_write(state_path, (json.dumps(status(preset_name, enabled)) + "\n").encode())
        clients = []
        for name, color in (("Mint", "#b7e8db"), ("Lilac", "#d6c5ef")):
            clients.append(
                session.launch(
                    ["qs", "-p", str(ROOT / "scripts/fixtures/fragment-lab.qml")],
                    name,
                    env=session.env
                    | {
                        "NIRIFX_LABEL": name,
                        "NIRIFX_COLOR": color,
                        "NIRIFX_DEMO_STATE": str(state_path),
                    },
                    private_bus=True,
                )
            )
            wait_for(
                lambda label=name: any(
                    window["title"].startswith("NiriFX Fragment Lab / " + label)
                    for window in session.windows()
                ),
                f"{name} fragment demo card",
            )
        session.focus()
        evidence = {
            "preview_pid": os.getpid(),
            "compositor_pid": session.compositor.pid,
            "outer_window_id": session.outer_id,
            "evidence": str(session.root),
            "config": str(session.config),
            "socket": session.env["NIRI_SOCKET"],
            "status_file": str(state_path),
            "build": build,
            "capability": capability,
        }
        atomic_write(
            ROOT / "artifacts/fragment-preview-ready.json",
            (json.dumps(evidence, indent=2) + "\n").encode(),
        )
        print(
            "Ready: choose Gentle, Tear, Cascade or Off in either card. "
            "Alt+1/2/3/0 selects; Alt+F floats; Alt+Left/Right reorders; Alt+Q exits.",
            flush=True,
        )
        # Each stream is generated by one owned synthetic process. No host IPC
        # event stream, imported file or arbitrary JSON can request activation.
        with (
            (session.root / "Mint.log").open() as mint,
            (session.root / "Lilac.log").open() as lilac,
        ):
            while session.compositor.poll() is None:
                if any(client.poll() is not None for client in clients):
                    break
                queued = [choice for stream in (mint, lilac) for choice in requests(stream)]
                if queued:
                    choice = queued[-1]
                    next_name = preset_name if choice == "off" else choice
                    next_enabled = choice != "off"
                    if (next_name, next_enabled) != (preset_name, enabled):
                        session.reload(config(next_name, movement_off=not next_enabled) + BINDS)
                        capability = fragment_capability(
                            binary, socket_path=session.env["NIRI_SOCKET"]
                        )
                        contract = capability["session"].get("contract", {})
                        if (
                            not capability["activation_ready"]
                            or contract.get("fragment_enabled") != next_enabled
                        ):
                            raise RuntimeError(f"Preset reload did not activate: {capability}")
                        preset_name, enabled = next_name, next_enabled
                        atomic_write(
                            state_path,
                            (json.dumps(status(preset_name, enabled)) + "\n").encode(),
                        )
                        print(f"Selected {status(preset_name, enabled)['name']}", flush=True)
                time.sleep(0.05)
        session.check_render_log()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preset", choices=PRESETS, default="tear")
    parser.add_argument("--list", action="store_true", help="List choices without launching Niri")
    args = parser.parse_args()
    if args.list:
        for key, preset in PRESETS.items():
            print(f"{key}: {preset.name} ({preset.particles} particles). {preset.description}")
        return

    def stop(*_):
        raise KeyboardInterrupt

    signal.signal(signal.SIGTERM, stop)
    try:
        run(args.preset)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
