"""Built-in starting styles. Every preset opts out of resize."""

from .model import Effect

PRESETS = {
    "subtle": Effect(
        scatter=35,
        open_ms=360,
        close_ms=300,
        gravity="none",
        particles=360,
        spin=55,
        dispersion=0.3,
        stagger=0.1,
    ),
    "balanced": Effect(),
    "dramatic": Effect(
        scatter=180,
        open_ms=680,
        close_ms=600,
        gravity="space",
        gravity_strength=1.1,
        particles=1100,
        spin=260,
        dispersion=1,
        stagger=0.26,
    ),
    "explosion": Effect(
        scatter=240,
        open_ms=700,
        close_ms=680,
        gravity="space",
        gravity_strength=1.5,
        particles=1200,
        spin=300,
        dispersion=1,
        stagger=0.12,
    ),
    "implosion": Effect(
        scatter=30,
        open_ms=720,
        close_ms=680,
        gravity="center",
        gravity_strength=1.65,
        particles=1000,
        spin=260,
        dispersion=1,
        stagger=0.2,
    ),
    "earth": Effect(
        scatter=65,
        open_ms=600,
        close_ms=650,
        gravity="down",
        gravity_strength=1.0,
        particles=600,
        spin=190,
        dispersion=0.85,
        stagger=0.24,
    ),
    "black-hole": Effect(
        scatter=12,
        open_ms=680,
        close_ms=650,
        gravity="center",
        gravity_strength=1.3,
        particles=800,
        rotation="gravity",
        spin=200,
        swirl=30,
        dispersion=0.55,
        stagger=0.22,
    ),
    "space": Effect(
        scatter=100,
        open_ms=650,
        close_ms=650,
        gravity="space",
        gravity_strength=0.9,
        particles=650,
        spin=210,
        dispersion=0.95,
        stagger=0.28,
    ),
    "vortex": Effect(
        scatter=25,
        open_ms=720,
        close_ms=720,
        gravity="center",
        gravity_strength=1.15,
        particles=720,
        rotation="gravity",
        spin=240,
        swirl=160,
        dispersion=0.65,
        stagger=0.25,
    ),
    "confetti": Effect(
        scatter=115,
        open_ms=650,
        close_ms=720,
        gravity="down",
        gravity_strength=0.85,
        particles=1600,
        spin=480,
        dispersion=1,
        stagger=0.3,
    ),
    "updraft": Effect(
        scatter=60,
        open_ms=600,
        close_ms=640,
        gravity="up",
        gravity_strength=0.9,
        particles=600,
        rotation="gravity",
        spin=180,
        swirl=-25,
        dispersion=0.8,
        stagger=0.24,
    ),
    "directional-wave": Effect(
        scatter=90,
        open_ms=1000,
        close_ms=1000,
        gravity="up",
        gravity_strength=0.6,
        particles=900,
        spin=180,
        release="left",
        wave_span=0.6,
    ),
    "corner-burst": Effect(
        scatter=180,
        open_ms=780,
        close_ms=740,
        gravity="space",
        gravity_strength=1.1,
        particles=1200,
        spin=300,
        origin_x=0.15,
        origin_y=0.8,
        dispersion=0.8,
    ),
    "orbital-collapse": Effect(
        scatter=15,
        open_ms=1000,
        close_ms=1000,
        gravity="center",
        gravity_strength=1.5,
        particles=1400,
        rotation="gravity",
        spin=320,
        swirl=300,
        dispersion=0.8,
        stagger=0.25,
    ),
    "slide-apart": Effect(
        family="slices",
        slice_count=12,
        slice_direction="alternate",
        slice_distance=240,
        slice_stagger=0.22,
        open_ms=680,
        close_ms=640,
    ),
    "alternating-blinds": Effect(
        family="slices",
        slice_count=16,
        slice_angle=90,
        slice_direction="alternate",
        slice_rotation=16,
        slice_distance=180,
        slice_stagger=0.35,
        open_ms=820,
        close_ms=760,
    ),
    "diagonal-shear": Effect(
        family="slices",
        slice_count=10,
        slice_angle=-35,
        slice_direction="alternate",
        slice_rotation=5,
        slice_distance=280,
        slice_stagger=0.3,
        open_ms=760,
        close_ms=720,
    ),
    "split-curtain": Effect(
        family="slices",
        slice_count=12,
        slice_distance=240,
        slice_stagger=0.22,
        open_ms=680,
        close_ms=640,
    ),
    "ribbon-wave": Effect(
        family="slices",
        slice_count=18,
        slice_direction="alternate",
        slice_distance=150,
        slice_stagger=0.2,
        slice_rotation=4,
        wave_strength=1,
        wave_frequency=0.6,
        wave_speed=1.5,
        open_ms=1100,
        close_ms=1050,
    ),
    "shuffled-slats": Effect(
        family="slices",
        slice_count=22,
        slice_direction="random",
        slice_order="random",
        slice_distance=260,
        slice_stagger=0.45,
        slice_rotation=28,
        slice_rotation_variation=1,
        slice_travel_variation=0.7,
        size_variation=1,
        direction_variation=0.45,
        open_ms=1000,
        close_ms=950,
    ),
    "venetian-sweep": Effect(
        family="slices",
        slice_count=20,
        slice_angle=90,
        slice_direction="positive",
        slice_order="center",
        slice_distance=260,
        slice_stagger=0.6,
        slice_rotation=12,
        wave_strength=0.8,
        wave_frequency=0.75,
        wave_speed=1,
        open_ms=1050,
        close_ms=1000,
    ),
    "tidal-fragments": Effect(
        scatter=100,
        particles=550,
        gravity="up",
        gravity_strength=0.6,
        wave_strength=1,
        wave_frequency=0.5,
        wave_speed=1.5,
        size_variation=0.5,
        spin=100,
        open_ms=1050,
        close_ms=1000,
    ),
    "mosaic-burst": Effect(
        scatter=200,
        particles=480,
        gravity="space",
        gravity_strength=1.1,
        size_variation=1,
        direction_variation=0.35,
        spin=220,
        open_ms=820,
        close_ms=780,
    ),
    "chaotic-confetti": Effect(
        scatter=100,
        particles=1100,
        gravity="down",
        gravity_strength=1.1,
        size_variation=0.9,
        direction_variation=0.85,
        wave_strength=0.5,
        wave_frequency=1.5,
        wave_speed=2,
        spin=540,
        dispersion=1,
        open_ms=1000,
        close_ms=1050,
    ),
    "crosswind": Effect(
        scatter=145,
        particles=850,
        gravity="right",
        gravity_strength=0.8,
        direction_variation=0.35,
        wave_strength=0.7,
        wave_frequency=0.5,
        wave_speed=1,
        spin=240,
        open_ms=900,
        close_ms=850,
    ),
    "orbital-ribbons": Effect(
        scatter=90,
        particles=680,
        gravity="center",
        gravity_strength=0.6,
        swirl=240,
        wave_strength=1,
        wave_frequency=0.75,
        wave_speed=1,
        size_variation=0.65,
        rotation="gravity",
        spin=220,
        open_ms=1050,
        close_ms=1000,
    ),
    "spring-wobble": Effect(
        family="elastic",
        elastic_strength=0.85,
        elastic_frequency=2.5,
        elastic_damping=1.5,
        open_ms=1000,
        close_ms=900,
    ),
    "rubber-band": Effect(
        family="elastic",
        elastic_strength=1,
        elastic_frequency=1.25,
        elastic_damping=0.8,
        elastic_axis="horizontal",
        open_ms=850,
        close_ms=800,
    ),
    "jelly": Effect(
        family="elastic",
        elastic_strength=0.9,
        elastic_frequency=3.5,
        elastic_damping=0.6,
        open_ms=1200,
        close_ms=1100,
    ),
    "pixel-dust": Effect(
        particles=1800,
        scatter=95,
        gravity="up",
        gravity_strength=0.65,
        fragment_shrink=0.9,
        fragment_roundness=0.25,
        spin=150,
        open_ms=850,
        close_ms=800,
    ),
    "bubble-burst": Effect(
        particles=180,
        scatter=160,
        gravity_strength=0.8,
        fragment_roundness=1,
        fragment_shrink=0.25,
        spin=80,
        open_ms=950,
        close_ms=900,
    ),
    "core-detonation": Effect(
        particles=1150,
        scatter=210,
        gravity_strength=1.4,
        release="center",
        wave_span=0.5,
        size_variation=0.35,
        fragment_roundness=0.15,
        fragment_shrink=0.4,
        spin=260,
        open_ms=1000,
        close_ms=950,
    ),
    "checker-scatter": Effect(
        particles=500,
        scatter=130,
        gravity="none",
        gravity_strength=0,
        release="checkerboard",
        wave_span=0.55,
        size_variation=0.3,
        fragment_shrink=0.35,
        spin=90,
        open_ms=1050,
        close_ms=1000,
    ),
    "hinged-fan": Effect(
        family="slices",
        slice_count=9,
        slice_distance=80,
        slice_rotation=45,
        slice_direction="positive",
        slice_pivot=-1,
        slice_stagger=0.5,
        slice_collapse=0.15,
        open_ms=950,
        close_ms=900,
    ),
    "venetian-shutter": Effect(
        family="slices",
        slice_count=18,
        slice_distance=0,
        slice_collapse=1,
        slice_stagger=0.6,
        slice_order="center",
        open_ms=950,
        close_ms=900,
    ),
    "ribbon-fold": Effect(
        family="slices",
        slice_count=14,
        slice_angle=90,
        slice_distance=180,
        slice_rotation=-30,
        slice_direction="alternate",
        slice_pivot=1,
        slice_collapse=0.8,
        wave_strength=0.5,
        size_variation=0.3,
        open_ms=1050,
        close_ms=1000,
    ),
    "zipper": Effect(
        family="slices",
        slice_count=22,
        slice_direction="alternate",
        slice_stagger=0.65,
        slice_distance=300,
        slice_collapse=0.5,
        open_ms=1050,
        close_ms=1000,
    ),
    "twist-snap": Effect(
        family="elastic",
        elastic_twist=65,
        elastic_strength=0.55,
        elastic_frequency=1.5,
        elastic_damping=1,
        elastic_stretch=0.25,
        open_ms=1000,
        close_ms=900,
    ),
    "flag-wave": Effect(
        family="elastic",
        elastic_axis="vertical",
        elastic_ripple=3,
        elastic_strength=1,
        elastic_frequency=2,
        elastic_damping=0.6,
        elastic_anchor="left",
        open_ms=1200,
        close_ms=1100,
    ),
    "corner-spring": Effect(
        family="elastic",
        elastic_twist=-32,
        elastic_stretch=0.5,
        elastic_anchor="bottom-left",
        elastic_frequency=1.5,
        elastic_damping=1,
        open_ms=1050,
        close_ms=1000,
    ),
    "accordion": Effect(
        family="elastic",
        elastic_axis="horizontal",
        elastic_ripple=2,
        elastic_stretch=0.9,
        elastic_frequency=1.25,
        elastic_strength=0.55,
        elastic_damping=1.2,
        open_ms=1150,
        close_ms=1100,
    ),
}

PRESETS.update(
    {
        "noise-dissolve": Effect(family="dissolve", edge_width=0, open_ms=850, close_ms=800),
        "ember-erosion": Effect(
            family="dissolve",
            dissolve_scale=36,
            dissolve_detail=0.7,
            dissolve_flow=0.45,
            dissolve_softness=0.045,
            dissolve_direction="down",
            dissolve_bias=0.65,
            edge_width=0.085,
            edge_char=0.85,
            edge_hue=25,
            open_ms=1050,
            close_ms=1000,
        ),
        "frost-vanish": Effect(
            family="dissolve",
            dissolve_scale=12,
            dissolve_direction="left",
            dissolve_bias=0.7,
            edge_width=0.09,
            edge_hue=190,
            edge_saturation=0.38,
            edge_char=0.15,
            dissolve_detail=0.8,
            dissolve_flow=0.2,
            open_ms=950,
            close_ms=900,
        ),
        "iris-bloom": Effect(family="iris", open_ms=750, close_ms=700),
        "diamond-turn": Effect(
            family="iris",
            iris_shape="diamond",
            iris_twist=100,
            iris_softness=0.025,
            open_ms=950,
            close_ms=900,
        ),
        "portal-out": Effect(
            family="iris",
            iris_direction="outward",
            iris_x=0.25,
            iris_y=0.65,
            iris_softness=0.1,
            open_ms=1000,
            close_ms=950,
        ),
    }
)

PRESETS.update(
    {
        "pixel-wipe": Effect(family="pixels", pixel_size=12, open_ms=1000, close_ms=950),
        "pixelate": Effect(
            family="pixels",
            pixel_mode="pixelate",
            pixel_size=28,
            pixel_randomness=1,
            open_ms=950,
            close_ms=900,
        ),
        "dust-drift": Effect(
            family="pixels",
            pixel_mode="dust",
            pixel_size=7,
            pixel_direction="left",
            pixel_randomness=0.32,
            pixel_travel=8,
            pixel_wind="up",
            open_ms=1250,
            close_ms=1200,
        ),
        "ghost-wisps": Effect(family="wisps", open_ms=1300, close_ms=1250),
        "ink-current": Effect(
            family="wisps",
            wisp_scale=72,
            wisp_strands=5,
            wisp_curl=1.1,
            wisp_angle=-35,
            wisp_drift=155,
            wisp_glow=0.85,
            edge_brightness=0.08,
            open_ms=1400,
            close_ms=1350,
        ),
        "shockwave": Effect(family="distortion", open_ms=1000, close_ms=950),
        "ripple-collapse": Effect(
            family="distortion",
            distortion_mode="ripple",
            distortion_strength=22,
            distortion_wavelength=95,
            distortion_cycles=2,
            distortion_falloff=0.7,
            open_ms=1150,
            close_ms=1100,
        ),
        "wave-fold": Effect(
            family="distortion",
            distortion_mode="wave",
            distortion_strength=36,
            distortion_wavelength=140,
            distortion_angle=25,
            distortion_cycles=1.25,
            distortion_falloff=0.4,
            open_ms=1150,
            close_ms=1100,
        ),
    }
)
